// zapateria-frontend/src/components/AsignacionMateriales.jsx
import { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import './AsignacionMateriales.css';

const api = axios.create({
  baseURL: 'http://localhost:3000/api'
});

export default function AsignacionMateriales() {
  const [asignaciones, setAsignaciones] = useState([]);
  const [pedidoFilter, setPedidoFilter] = useState('');
  const [modeloFilter, setModeloFilter] = useState('');
  const [estadoFilter, setEstadoFilter] = useState('');

  useEffect(() => {
    async function cargar() {
      try {
        const response = await api.get('/materiales/asignaciones');
        setAsignaciones(response.data || []);
      } catch (error) {
        console.error('Error cargando asignaciones:', error);
      }
    }
    cargar();
  }, []);

  const asignacionesFiltradas = useMemo(() => {
    const pedido = pedidoFilter.trim().toLowerCase();
    const modelo = modeloFilter.trim().toLowerCase();
    const estado = estadoFilter.trim().toLowerCase();

    return asignaciones.filter((item) => {
      const pedidoMatch = pedido === '' || String(item.id_pedido).toLowerCase().includes(pedido);
      const modeloMatch = modelo === '' || String(item.modelo || '').toLowerCase().includes(modelo);
      const estadoMatch = estado === '' || String(item.estado || '').toLowerCase().includes(estado);
      return pedidoMatch && modeloMatch && estadoMatch;
    });
  }, [asignaciones, pedidoFilter, modeloFilter, estadoFilter]);

  const estadoClass = (estado) => {
    const value = String(estado || '').trim().toLowerCase();
    if (value === 'reservado') return 'estado-chip reservado';
    if (value === 'parcial') return 'estado-chip parcial';
    if (value === 'sin stock' || value === 'sin_stock' || value === 'faltante' || value === 'no stock') return 'estado-chip sin-stock';
    return 'estado-chip';
  };

  return (
    <div className="asignacion-materiales-screen">
      <div className="asignacion-header">
        <div>
          <h2>Asignación de Materiales</h2>
          <p>Consulta el estado de la reserva de materiales por pedido.</p>
        </div>
      </div>

      <div className="asignacion-filters">
        <div className="filter-item">
          <label>Pedido</label>
          <input
            type="text"
            value={pedidoFilter}
            onChange={(e) => setPedidoFilter(e.target.value)}
            placeholder="Buscar por pedido"
          />
        </div>
        <div className="filter-item">
          <label>Modelo</label>
          <input
            type="text"
            value={modeloFilter}
            onChange={(e) => setModeloFilter(e.target.value)}
            placeholder="Buscar por modelo"
          />
        </div>
        <div className="filter-item">
          <label>Estado</label>
          <input
            type="text"
            value={estadoFilter}
            onChange={(e) => setEstadoFilter(e.target.value)}
            placeholder="Buscar por estado"
          />
        </div>
      </div>

      <div className="table-responsive">
        <table className="asignacion-table-react">
          <thead>
            <tr>
              <th>Pedido</th>
              <th>Modelo</th>
              <th>Material</th>
              <th>Cantidad necesaria</th>
              <th>Cantidad reservada</th>
              <th>Cantidad faltante</th>
              <th>Estado</th>
            </tr>
          </thead>
          <tbody>
            {asignacionesFiltradas.length === 0 ? (
              <tr>
                <td colSpan={7} className="empty-row">
                  No hay resultados para los filtros seleccionados.
                </td>
              </tr>
            ) : (
              asignacionesFiltradas.map((item) => (
                <tr key={`${item.id_pedido}-${item.material}`}>
                  <td>#{item.id_pedido}</td>
                  <td>{item.modelo || 'N/D'}</td>
                  <td>{item.material}</td>
                  <td>{item.cantidad_necesaria}</td>
                  <td>{item.cantidad_reservada}</td>
                  <td>{item.cantidad_faltante}</td>
                  <td>
                    <span className={estadoClass(item.estado)}>{item.estado}</span>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// zapateria-frontend/src/views/AsignacionMateriales.vue
<template>
  <div class="asignacion-materiales-view">
    <section class="filter-row">
      <div class="filter-item">
        <label>Pedido</label>
        <input v-model="filtroPedido" placeholder="Buscar pedido" />
      </div>
      <div class="filter-item">
        <label>Modelo</label>
        <input v-model="filtroModelo" placeholder="Buscar modelo" />
      </div>
      <div class="filter-item">
        <label>Estado</label>
        <input v-model="filtroEstado" placeholder="Buscar estado" />
      </div>
    </section>

    <section class="table-wrapper">
      <div class="table-responsive">
        <table class="asignacion-table">
          <thead>
            <tr>
              <th>Pedido</th>
              <th>Modelo</th>
              <th>Material</th>
              <th>Cantidad necesaria</th>
              <th>Cantidad reservada</th>
              <th>Cantidad faltante</th>
              <th>Estado</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="item in asignacionesFiltradas" :key="item.id_pedido + '-' + item.material">
              <td>#{{ item.id_pedido }}</td>
              <td>{{ item.modelo || 'N/D' }}</td>
              <td>{{ item.material }}</td>
              <td>{{ item.cantidad_necesaria }}</td>
              <td>{{ item.cantidad_reservada }}</td>
              <td>{{ item.cantidad_faltante }}</td>
              <td>
                <span :class="estadoClass(item.estado)">{{ item.estado }}</span>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div v-if="!asignacionesFiltradas.length" class="empty-state">
        No hay asignaciones que coincidan con los filtros.
      </div>
    </section>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import '../styles/AsignacionMateriales.css';
import { listarAsignaciones } from '../services/materiales';

const asignaciones = ref([]);
const filtroPedido = ref('');
const filtroModelo = ref('');
const filtroEstado = ref('');

const cargarAsignaciones = async () => {
  try {
    asignaciones.value = await listarAsignaciones();
  } catch (error) {
    console.error('Error cargando asignaciones', error);
  }
};

const estadoClass = (estado) => {
  const value = String(estado || '').trim().toLowerCase();
  return {
    'estado-chip': true,
    reservado: value === 'reservado',
    parcial: value === 'parcial',
    'sin-stock': value === 'sin stock' || value === 'sin_stock' || value === 'faltante' || value === 'no stock'
  };
};

const asignacionesFiltradas = computed(() => {
  const pedido = filtroPedido.value.trim().toLowerCase();
  const modelo = filtroModelo.value.trim().toLowerCase();
  const estado = filtroEstado.value.trim().toLowerCase();

  return asignaciones.value.filter((item) => {
    const matchesPedido = pedido === '' || String(item.id_pedido).includes(pedido);
    const matchesModelo = modelo === '' || String(item.modelo || '').toLowerCase().includes(modelo);
    const matchesEstado = estado === '' || String(item.estado || '').toLowerCase().includes(estado);
    return matchesPedido && matchesModelo && matchesEstado;
  });
});

onMounted(cargarAsignaciones);
</script>
